GRANT USAGE ON SCHEMA public TO river_go_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO river_go_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO river_go_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO river_go_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES TO river_go_app;
